### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by dacb** [CNNs4QSPR/cnns4qspr#2]
I only looked in master, but I saw some issues with your repo structure (thought it looks like you might be working on this).  Make sure you follow the repository layout pattern in this PDF: https://github.com/UWDIRECT/UWDIRECT.github.io/raw/master/Wi20_content/SEDS/L9.Project_Structure.pdf

Some things I saw... The module directory did not have  an `__init__.py`.  Also, in the module directory, there shouldn't be any jupyter notebooks, except maybe in a `demo` directory, though that is often in the repo root, not the module directory.  No unit tests!  I'll make a separate issue about this.  You have directories like `se3cnn_v3` in the repo root.  These look like specific training runs.  That can be fine, though you may want to organize them in a `models` directory in the repo root and then use README.md in the `models` or the repo root to explain what they are.

**Comment by davidcjuergens** [comment]
@dacb Fixed repo structure, okay to close this?

**Comment by dacb** [comment]
Looks great!
