### ISSUE TITLE
Unit tests and continuous integration

### ISSUE THREAD

**Issue by dacb** [CNNs4QSPR/cnns4qspr#3]
Where are you unit tests?!?!!

Make sure you have a full complement of unit tests and are using continuous integration. You can use the template from the repository I demoed: https://github.com/dacb/codebase_conda

Make sure to put badges in your README.md in the repo root.

**Comment by davidcjuergens** [comment]
@dacb Hey could you check out the .travis.yml thing I've written so far. I have no idea if I'm even close to doing this correctly, but here's what I'm trying to do:

1. Install Anaconda 
2. make a test environment with python 3.6
3. Install 2 github repos into the environment site packages - one is called `lie_learn` and one is called  `se3cnn`. The way we've been installing these into our environments is going into the environment site packages, cloning the repos, stepping inside the repos and running `python setup.py install` for both. `lie-learn` is a dependency of `se3cnn`, so we do `lie-learn` first. 
4. obviously once that environment is set up, I want to run some unit tests, but for now I just wanted to do something I know would work, so I call `echo "Hello, Travis"`

Am I on the right track? When I wrote the commands in the `install:` section of the yml, I was assuming I was interacting with a bash shell.

**Comment by davidcjuergens** [comment]
CI implemented!
