### ISSUE TITLE
problem with unit test in test_visualizer

### ISSUE THREAD

**Issue by davidcjuergens** [CNNs4QSPR/cnns4qspr#5]
Hey @nisargjoshi10 I'm just leaving this here so we don't forget, either one of us can take a look at this whenever. The unit test in `test_visualizer.py` might be broken, but seems like it'll be a small fix! Here is the error:

`File "/home/travis/build/CNNs4QSPR/cnns4qspr/cnns4qspr/test/test_visualizer.py",`
`line 15, in test_visualizer`
    `self.path = 'cnns4qspr/formatting_data/sample_pdbs/1a00B00'`
`NameError: name 'self' is not defined`

**Comment by nisargjoshi10** [comment]
yeah sounds good!

**Comment by davidcjuergens** [comment]
problem solved, closing this issue
