### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by oriondollar** [CNNs4QSPR/cnns4qspr#7]
checkpoints folder and .ckpt files don't download through pip install

**Comment by oriondollar** [comment]
needed `MANIFEST.in`. problem fixed.

**Comment by bhavaygg** [comment]
@oriondollar I am facing the same problem and I am working on colab. How can i fix this?

**Comment by oriondollar** [comment]
@Chokerino if the .ckpts aren't downloading automatically you can also find them [here](https://drive.google.com/drive/folders/1Y3Dtk72I_A6bSoPXZ0wamCXMzJeQVs6X?usp=sharing)

**Comment by bhavaygg** [comment]
@oriondollar I am trying to featurize my proteins but the colab sessions keeps crashing. How much RAM is expected to be used to featurize about 500 proteins?
